_extends: .github
repository:
  name: zillowtoynab
  description: link a ynab account to a zillow property
  homepage: https://github.com/saiichihashimoto/zillowtoynab/
  topics: ynab, you need a budget, zestimate, zillow
