_extends: .github
repository:
  name: zillowtoynab
  description: link a ynab account to a zillow property
  homepage: https://zillowtoynab.com
  topics: ynab, you need a budget, zestimate, zillow
branches:
  - name: master
    protection:
      required_status_checks:
        contexts: ['Semantic Pull Request', 'Travis CI - Pull Request', 'coverage/coveralls']
  - name: gh-pages
    protection:
      enforce_admins: true
