language: node_js
cache: npm
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - saiichihashimoto@gmail.com
    on_success: never
    on_failure: always
script: npm test -- -- --color --coverage
after_script:
  - cat ./coverage/lcov.info | npx coveralls
jobs:
  include:
    - stage: test
      if: type = pull_request
    - stage: release
      if: type = push
      before_deploy: cross-env REACT_APP_BACKEND_URL=https://zillowtoynab.herokuapp.com npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
